title: Intelligent solutions for self-interference cancellation and signal redefinition in integrated sensing and communications
logo: assets/img/6G.img
show_downloads: false
theme: jekyll-theme-minimal
